name: Build & test on Linux

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup OCaml
              uses: ocaml/setup-ocaml@v3
              with:
                  ocaml-compiler: 5.0.0

            - name: Opam dependencies
              run: opam install --locked --deps-only -t .

            - name: Build
              run: opam exec -- dune build

            - name: Runtest
              run: opam exec -- dune runtest
